=== vadosnaprimer/pspkvm/pspkvm-v0_3_1-20080408/midp/src/configuration/configuration_xml/share/configuration.dtd
<!--
        	

        Copyright  1990-2007 Sun Microsystems, Inc. All Rights Reserved.
        DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
        
        This program is free software; you can redistribute it and/or
        modify it under the terms of the GNU General Public License version
        2 only, as published by the Free Software Foundation.
        
        This program is distributed in the hope that it will be useful, but
        WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
        General Public License version 2 for more details (a copy is
        included at /legal/license.txt).
        
        You should have received a copy of the GNU General Public License
        version 2 along with this work; if not, write to the Free Software
        Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
        02110-1301 USA
        
        Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa
        Clara, CA 95054 or visit www.sun.com if you need additional
        information or have any questions.
-->
<!ELEMENT configuration (properties | constants | localized_strings | skin | rawimage | permissions)*>
<!ELEMENT properties (property)+>
<!ELEMENT property EMPTY>
<!-- If callout is specified, it must be a defined native function -->
<!--  with the signature: char* foo(void) -->
<!ATTLIST property
        Key      CDATA                          #REQUIRED
        Value    CDATA                          #REQUIRED
        Scope    (system | internal)            "internal"
        Callout  CDATA                          #IMPLIED
        Comment  CDATA                          #IMPLIED
>

<!ELEMENT localized_strings (localized_string)*>
    
<!-- 
    KeysClass: name of constants class that provides keys values.   
 -->
<!ATTLIST localized_strings
    Package     CDATA                           #REQUIRED
    Name        CDATA                           #REQUIRED
    KeysClass   CDATA                           #REQUIRED 
    Scope       (protected | public)            "public"
    Comment     CDATA                           #IMPLIED
>
<!ELEMENT localized_string EMPTY>
<!ATTLIST localized_string
        Key         CDATA                   #REQUIRED
        KeyValue    CDATA                   #IMPLIED
        Value       CDATA                   #REQUIRED
>

<!ELEMENT constants (constant_class)*>
<!ELEMENT constant_class (constant)*>

<!--
    KeysValuesProvider: does this class provide keys values.
    
    AutoValue: automatically generate integer values for constants
    (starting from zero and going up).

    JavaOnly: generate only .java file for constants.
    NativeOnly: generate only native definitions for constants.
-->
<!ATTLIST constant_class
    Package  CDATA                          #REQUIRED
    Name     CDATA                          #REQUIRED
    Scope    (protected | public)           "public"
    Comment  CDATA                          #IMPLIED
    KeysValuesProvider (true | false)       "false"
    AutoValue  (true | false)               "false"
    JavaOnly   (true | false)               "false"
    NativeOnly (true | false)               "false"
>

<!ELEMENT constant EMPTY>
<!ATTLIST constant
    Type      (int | String | boolean)       #IMPLIED
    Name      CDATA                          #REQUIRED
    Value     CDATA                          #IMPLIED
    VScope    (protected | public | private) "public"
    Comment   CDATA                          #IMPLIED
    JavaOnly   (true | false)                "false"
    NativeOnly (true | false)                "false"
>

<!--
    Top level node for skin description
-->
<!ELEMENT skin (skin_properties)>


<!--
    Skin properties description
-->
<!ELEMENT skin_properties (integer | integer_seq | string | font | 
        image | composite_image)+>
<!ATTLIST skin_properties
    KeysClass   CDATA                           #REQUIRED 
>

<!--
    Integer valued skin property
-->
<!ELEMENT integer EMPTY>
<!ATTLIST integer
        Key         CDATA                   #REQUIRED
        KeyValue    CDATA                   #IMPLIED
        Value       CDATA                   #REQUIRED
>

<!--
    Integers sequence valued skin property
-->
<!ELEMENT integer_seq EMPTY>
<!ATTLIST integer_seq
        Key         CDATA                   #REQUIRED
        KeyValue    CDATA                   #IMPLIED
        Value       CDATA                   #REQUIRED
>

<!--
    String valued skin property
-->
<!ELEMENT string EMPTY>
<!ATTLIST string
        Key         CDATA                   #REQUIRED
        KeyValue    CDATA                   #IMPLIED
        Value       CDATA                   #REQUIRED
>

<!--
    Font valued skin property
-->
<!ELEMENT font EMPTY>
<!ATTLIST font
        Key         CDATA                   #REQUIRED
        KeyValue    CDATA                   #IMPLIED
        Value       CDATA                   #REQUIRED
>

<!--
    Image valued skin property
-->
<!ELEMENT image EMPTY>
<!ATTLIST image
        Key         CDATA                   #REQUIRED
        KeyValue    CDATA                   #IMPLIED
        Value       CDATA                   #REQUIRED
        Romized     (true | false)          "false"
>

<!--
    Composite image valued skin property
-->
<!ELEMENT composite_image EMPTY>
<!ATTLIST composite_image
        Key         CDATA                   #REQUIRED
        KeyValue    CDATA                   #IMPLIED
        Value       CDATA                   #REQUIRED
        Pieces      CDATA                   #REQUIRED
        Romized     (true | false)          "false"
>

<!--
    Raw image format description
-->
<!ELEMENT rawimage EMPTY>
<!ATTLIST rawimage
        Format    (Putpixel | ARGB)         #REQUIRED
        Colors    (565 | 888)               #REQUIRED
        Endian    (Little | Big)            #REQUIRED
>

<!--
    Extended permissions description
-->
<!ELEMENT permissions (group)*>
<!ELEMENT group (permission)*>
<!ATTLIST group
        ID          CDATA                   #REQUIRED
>
<!ELEMENT permission EMPTY>
<!ATTLIST permission
        ID          CDATA                   #REQUIRED
        Name        CDATA                   #REQUIRED
>

=== vadosnaprimer/pspkvm/branches/transformers/midp/src/configuration/configuration_xml/javacall/properties.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "../share/configuration.dtd">
<!--
		Copyright  1990-2007 Sun Microsystems, Inc. All Rights Reserved.
		DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
		
		This program is free software; you can redistribute it and/or
		modify it under the terms of the GNU General Public License version
		2 only, as published by the Free Software Foundation.
		
		This program is distributed in the hope that it will be useful, but
		WITHOUT ANY WARRANTY; without even the implied warranty of
		MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
		General Public License version 2 for more details (a copy is
		included at /legal/license.txt).
		
		You should have received a copy of the GNU General Public License
		version 2 along with this work; if not, write to the Free Software
		Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
		02110-1301 USA
		
		Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa
		Clara, CA 95054 or visit www.sun.com if you need additional
		information or have any questions.
-->
<!-- THIS IS THE PROPERTIES FILE FOR SHARP ZAURUS 5500D ONLY!
	 YOU MAY NEED TO ADJUST THAT TO YOUR PLATFORM -->
<configuration>
<properties>
<!-- INTERNAL PROPERTIES -->
<!-- Visible from Configuration.getProperty() -->
  <!-- System tunable parameters -->

  <!-- Default values for SMS internal implementation -->
  <property Key="com.sun.midp.io.j2me.sms.Impl" 
		Value="com.sun.midp.io.j2me.sms.DatagramImpl" 
		Scope="internal"
		Comment="Select the low level transport handler."/>
  <property Key="com.sun.midp.io.j2me.sms.DatagramHost" 
		Value="smsdatagramhost"
		Comment="The datagram host name."/>
  <property Key="com.sun.midp.io.j2me.sms.DatagramPortIn" 
		Value="54321" 
		Scope="internal"
		Comment="The datagram port number for inbound messages from the SMS emulator."/>
  <property Key="com.sun.midp.io.j2me.sms.DatagramPortOut" 
		Value="12345" 
		Scope="internal"
		Comment="The datagram port number of a SMS emulator."/>

  <!-- Alternate SMS port for CBS emulation -->
  <property Key="com.sun.midp.io.j2me.sms.CBSPort" 
		Value="24680" 
		Scope="internal"
		Comment="Create a CBS message connection protocol port number"/>

  <!-- Sender's phone number -->
  <property Key="com.sun.midp.io.j2me.sms.PhoneNumber" 
		Value="+5551212" 
		Scope="internal"
		Comment="The phone number for outbound messages from the SMS emulator."/>

  <!-- Default SMS Service Center address -->
  <property Key="wireless.messaging.sms.smsc" 
		Value="+17815511212" 
		Scope="internal"
		Comment="Default SMS Service Center address."/>
  <property Key="VmDebuggerPort"
		Value="2808"
		Scope="internal"
		Comment="Default SMS Service Center address port number."/>
</properties>
</configuration>

=== vadosnaprimer/pspkvm/tags/pspkvm-v0_3_0-20080331/midp/src/configuration/configuration_xml/wince/sp176x220.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "../share/configuration.dtd">
<!--
        	

        Copyright  1990-2007 Sun Microsystems, Inc. All Rights Reserved.
        DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
        
        This program is free software; you can redistribute it and/or
        modify it under the terms of the GNU General Public License version
        2 only, as published by the Free Software Foundation.
        
        This program is distributed in the hope that it will be useful, but
        WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
        General Public License version 2 for more details (a copy is
        included at /legal/license.txt).
        
        You should have received a copy of the GNU General Public License
        version 2 along with this work; if not, write to the Free Software
        Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
        02110-1301 USA
        
        Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa
        Clara, CA 95054 or visit www.sun.com if you need additional
        information or have any questions.
-->
<configuration>
<constants>
<constant_class Package="com.sun.midp.configurator" Name="Constants" Scope="public">

  <constant Type="int"
            Name="CHAM_WIDTH"
            Value="176"
            Comment="(Chameleon Only) display width (QVA PocketPC)"/>
  <constant Type="int"
            Name="CHAM_HEIGHT"
            Value="180"
            Comment="(Chameleon Only) display height (QVA PocketPC)"/>
  <constant Type="int"
            Name="CHAM_FULLHEIGHT"
            Value="180"
            Comment="(Chameleon Only) full display height (QVA PocketPC)"/>

  <constant Type="int"
            Name="FULLWIDTH"
            Value="176"
            Comment="(Fixed) full display width"/>
  <constant Type="int"
            Name="FULLHEIGHT"
            Value="180" 
            Comment="(Fixed) full display height"/>
  <constant Type="int"
            Name="NORMALWIDTH"
            Value="176" 
            Comment="(Fixed) normal width"/>
  <constant Type="int"
            Name="NORMALHEIGHT"
            Value="180" 
            Comment="(Fixed) normal height"/>

  <constant Type="int"
            Name="JWC_WINCE_SMARTPHONE"
            Value="1"
            Comment="Specify whether we are building for smartphone"/>
  <constant Type="int"
            Name="JWC_WINCE_TITLE_HEIGHT"
            Value="20"
            Comment="Height of the WinCE title at the top of LCD"/>
  <constant Type="int"
            Name="JWC_WINCE_MENU_HEIGHT"
            Value="20"
            Comment="Height of the WinCE menu at the bottom of LCD"/>

  <constant Type="int"
            Name="AMS_ITEM_WIDTH"
            Value="150"
            Comment="Width of item in AMS screen"/>
</constant_class>
</constants>
</configuration>

=== vadosnaprimer/pspkvm/pspkvm-v0_3_1-20080408/midp/src/configuration/configuration_xml/share/alert_type_constants.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "./configuration.dtd">
<!--


        Copyright  1990-2007 Sun Microsystems, Inc. All Rights Reserved.
        DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
        
        This program is free software; you can redistribute it and/or
        modify it under the terms of the GNU General Public License version
        2 only, as published by the Free Software Foundation.
        
        This program is distributed in the hope that it will be useful, but
        WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
        General Public License version 2 for more details (a copy is
        included at /legal/license.txt).
        
        You should have received a copy of the GNU General Public License
        version 2 along with this work; if not, write to the Free Software
        Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
        02110-1301 USA
        
        Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa
        Clara, CA 95054 or visit www.sun.com if you need additional
        information or have any questions.
-->

<configuration>
<constants>

<constant_class Package="com.sun.midp.configurator" Name="AlertTypeConstants"
    Scope="public" Comment="/** Constants for alert types */">
  <constant Type="int"
            Name="LCDUI_ALERT_TYPE_INFO"
            Value="1"
            Comment="Information Alert"/>
  <constant Type="int"
            Name="LCDUI_ALERT_TYPE_WARNING"
            Value="2"
            Comment="Warning Alert"/>
  <constant Type="int"
            Name="LCDUI_ALERT_TYPE_ERROR"
            Value="3"
            Comment="Error Alert"/>
  <constant Type="int"
            Name="LCDUI_ALERT_TYPE_ALARM"
            Value="4"
            Comment="Alarm Alert"/>
  <constant Type="int"
            Name="LCDUI_ALERT_TYPE_CONFIRMATION"
            Value="5"
            Comment="Confirmation Alert"/>
</constant_class>

</constants>
</configuration>

=== vadosnaprimer/pspkvm/branches/deadbeef/midp/src/configuration/configuration_xml/linux_qte/platform_widget.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "../share/configuration.dtd">
<!--
        	

        Copyright  1990-2007 Sun Microsystems, Inc. All Rights Reserved.
        DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
        
        This program is free software; you can redistribute it and/or
        modify it under the terms of the GNU General Public License version
        2 only, as published by the Free Software Foundation.
        
        This program is distributed in the hope that it will be useful, but
        WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
        General Public License version 2 for more details (a copy is
        included at /legal/license.txt).
        
        You should have received a copy of the GNU General Public License
        version 2 along with this work; if not, write to the Free Software
        Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
        02110-1301 USA
        
        Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa
        Clara, CA 95054 or visit www.sun.com if you need additional
        information or have any questions.
        
        This source file is specific for Qt-based configurations.
-->
<configuration>
<constants>
<constant_class Package="com.sun.midp.configurator" Name="Constants" Scope="public">
<!-- Package javax.microedition.lcdui -->
  <constant Type="int"
	    Name="ALERT_NUM_OF_BUTTONS"
	    Value="3"
	    Comment="Number of buttons for abstract commands."/>
  <constant Type="int"
	    Name="ALERT_BUTTON_WIDTH"
	    Value="40"
	    Comment="Width of an abstract command."/>
  <constant Type="int"
	    Name="ALERT_BUTTON_HEIGHT"
	    Value="20"
	    Comment="Height of an abstract command."/>
  <constant Type="int"
	    Name="ALERT_CELL_SPACING"
	    Value="4"
	    Comment="Space between image, text and buttons."/>
  <constant Type="int"
	    Name="ALERT_WIDTH"
	    Value="140"
	    Comment="Width of the alert dialog window."/>
  <constant Type="int"
	    Name="ALERT_HEIGHT"
	    Value="120"
	    Comment="Height of the alert dialog window."/>
  <constant Type="int"
        Name="PAD_CHOICE_POPUP_BUTTON"
        Value="16"
        NativeOnly="true"
        Comment="Subtract this constant from the button width() to get
                 space available for the button text."/>
    <constant Type="int"
          Name="PAD_CAPTION"
          Value="8"
          NativeOnly="true"
          Comment="Space between buttons and around the text, in pixels.
                   Qt's qwsDecoration does not take it into account."/>
 </constant_class>
</constants>
</configuration>

=== vadosnaprimer/pspkvm/branches/jsr179/jsr120/build/share/config/properties_jsr120.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "configuration.dtd">
<!--
    
  
  Copyright  1990-2007 Sun Microsystems, Inc. All Rights Reserved.
  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
  
  This program is free software; you can redistribute it and/or
  modify it under the terms of the GNU General Public License version
  2 only, as published by the Free Software Foundation.
  
  This program is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  General Public License version 2 for more details (a copy is
  included at /legal/license.txt).
  
  You should have received a copy of the GNU General Public License
  version 2 along with this work; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
  02110-1301 USA
  
  Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa
  Clara, CA 95054 or visit www.sun.com if you need additional
  information or have any questions.
  
-->
<!-- System-independent JSR 205 properties required by the specification -->
<configuration>
  <properties>
    <!-- SYSTEM PROPERTIES -->
    <!-- Visible from System.getProperty() -->

    <property Key="wireless.messaging.version"
      Value="1.1"
      Scope="system"
      Comment="WMA version number."/>

    <property Key="wireless.messaging.sms.smsc"
      Value="+17815511212"
      Scope="system"
      Comment="Default SMS Service Center address."/>
    
    <!-- INTERNAL PROPERTIES -->
    <!-- Visible from Configuration.getProperty() -->
    <property Key="com.sun.midp.io.j2me.wma.DatagramHost"
      Value="wmadatagramhost"
      Comment="The datagram host name for wma emulated messages."/>
    
    <property Key="com.sun.midp.io.j2me.sms.DatagramPortIn"
      Value="11100"
      Scope="internal"
      Comment="The datagram port number for inbound SMS messages."/>
    
    <property Key="com.sun.midp.io.j2me.sms.DatagramPortOut"
      Value="11101"
      Scope="internal"
      Comment="The datagram port number of outbound SMS messages."/>
    
    <property Key="com.sun.midp.io.j2me.cbs.DatagramPortIn"
      Value="22200"
      Scope="internal"
      Comment="The datagram port number for inbound CBS messages."/>
    
    <property Key="com.sun.midp.io.j2me.sms.PhoneNumber"
      Value="+5551212"
      Scope="internal"
      Comment="The phone number for outbound messages from the SMS emulator."/>
    
  </properties>
</configuration>

=== vadosnaprimer/pspkvm/branches/jsr239/jsr239/src/cldc-oi/config/properties_jsr239.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "configuration.dtd">
<!--
   

  Copyright  1990-2007 Sun Microsystems, Inc. All Rights Reserved.
  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
  
  This program is free software; you can redistribute it and/or
  modify it under the terms of the GNU General Public License version
  2 only, as published by the Free Software Foundation.
  
  This program is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  General Public License version 2 for more details (a copy is
  included at /legal/license.txt).
  
  You should have received a copy of the GNU General Public License
  version 2 along with this work; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
  02110-1301 USA
  
  Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa
  Clara, CA 95054 or visit www.sun.com if you need additional
  information or have any questions.

-->
<configuration>
<properties>
<!-- System  properties (visible via System.getProperty() -->
  <property Key="microedition.khronos.egl.version"
      Value="1.1"
      Scope="system"
      Comment="The version of EGL API."/>
      
  <property Key="microedition.khronos.opengles.version"
      Value="1.1"
      Scope="system"
      Comment="The version of OpenGL ES API."/>

<!-- Internal properties (visible via Configuration.getProperty() -->
  <property Key="jsr239.noqueue"
      Value="false"
      Scope="internal"
      Comment="Flush queue after each command."/>
      
  <property Key="jsr239.supportsEGL11"
      Value="true"
      Scope="internal"
      Comment="Whether native library supports EGL 1.1."/>

  <property Key="jsr239.supportsGL11"
      Value="true"
      Scope="internal"
      Comment="Whether native library supports GL 1.1."/>

  <property Key="jsr239.supports_OES_query_matrix"
      Value="true"
      Scope="internal"
      Comment="Whether the extension is supported."/>
      
  <property Key="jsr239.supports_OES_draw_texture"
      Value="true"
      Scope="internal"
      Comment="Whether the extension is supported."/>

  <property Key="jsr239.supports_OES_matrix_palette"
      Value="true"
      Scope="internal"
      Comment="Whether the extension is supported."/>

  <property Key="jsr239.supports_OES_texture_cube_map"
      Value="false"
      Scope="internal"
      Comment="Whether the extension is supported."/>

  <property Key="jsr239.supports_OES_texture_env_crossbar"
      Value="false"
      Scope="internal"
      Comment="Whether the extension is supported."/>

  <property Key="jsr239.supports_OES_texture_mirrored_repeat"
      Value="false"
      Scope="internal"
      Comment="Whether the extension is supported."/>
      
  <property Key="jsr239.supports_OES_blend_subtract"
      Value="false"
      Scope="internal"
      Comment="Whether the extension is supported."/>

  <property Key="jsr239.supports_OES_blend_func_separate"
      Value="false"
      Scope="internal"
      Comment="Whether the extension is supported."/>

  <property Key="jsr239.supports_OES_blend_equation_separate"
      Value="false"
      Scope="internal"
      Comment="Whether the extension is supported."/>
      
  <property Key="jsr239.supports_OES_stencil_wrap"
      Value="false"
      Scope="internal"
      Comment="Whether the extension is supported."/>

  <property Key="jsr239.supports_OES_extended_matrix_palette"
      Value="false"
      Scope="internal"
      Comment="Whether the extension is supported."/>

  <property Key="jsr239.supports_OES_framebuffer_object"
      Value="false"
      Scope="internal"
      Comment="Whether the extension is supported."/>

</properties>
</configuration>

=== vadosnaprimer/pspkvm/tags/pspkvm-v0_3_1-20080408/midp/src/configuration/configuration_xml/linux_fb/constants_omap730.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "../share/configuration.dtd">
<!--
        Copyright  1990-2007 Sun Microsystems, Inc. All Rights Reserved.
        DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
        
        This program is free software; you can redistribute it and/or
        modify it under the terms of the GNU General Public License version
        2 only, as published by the Free Software Foundation.
        
        This program is distributed in the hope that it will be useful, but
        WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
        General Public License version 2 for more details (a copy is
        included at /legal/license.txt).
        
        You should have received a copy of the GNU General Public License
        version 2 along with this work; if not, write to the Free Software
        Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
        02110-1301 USA
        
        Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa
        Clara, CA 95054 or visit www.sun.com if you need additional
        information or have any questions.
-->
<configuration>
<constants>
<constant_class Package="com.sun.midp.configurator" Name="Constants" Scope="public">
  <constant Type="boolean"
            Name="POINTER_SUPPORTED"
            Value="false" 
            Comment="Whether both the platform and MIDP implementation provide support for a pointer (press and release). Set to true when pointer is supported; set to false when pointer is not supported."/>
  <constant Type="boolean"
            Name="MOTION_SUPPORTED"
            Value="false" 
            Comment="If your platform supports pointer motion and you want MIDP implementation provides support for pointer motions, set it to true; otherwise, set it to false so that MIDP runtime can provide this information to MIDlet."/>
  <constant Type="boolean"
            Name="REPEAT_SUPPORTED"
            Value="true" 
            Comment="If your platform support key repeat and you want MIDP implementation provides support for key repeat, set this to true, otherwise set it to false."/>
  <constant Type="int"
             Name="REPEAT_TIMEOUT"
             Value="400"
             Comment="If your platform support key repeat and you want MIDP implementation needs to support key repeat, set this to value of timeout before repeat key event generation."/>
  <constant Type="int"
             Name="REPEAT_PERIOD"
             Value="80"
             Comment="If your platform support key repeat and you want MIDP implementation needs to support key repeat, set this to value of period between next repeat key event generation."/>
 </constant_class>
</constants>
</configuration>
