=== vadosnaprimer/pspkvm/pspkvm-v0_3_1-20080408/midp/src/configuration/configuration_xml/share/configuration.dtd
<!--
        	

        Copyright  1990-2007 Sun Microsystems, Inc. All Rights Reserved.
        DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
        
        This program is free software; you can redistribute it and/or
        modify it under the terms of the GNU General Public License version
        2 only, as published by the Free Software Foundation.
        
        This program is distributed in the hope that it will be useful, but
        WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
        General Public License version 2 for more details (a copy is
        included at /legal/license.txt).
        
        You should have received a copy of the GNU General Public License
        version 2 along with this work; if not, write to the Free Software
        Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
        02110-1301 USA
        
        Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa
        Clara, CA 95054 or visit www.sun.com if you need additional
        information or have any questions.
-->
<!ELEMENT configuration (properties | constants | localized_strings | skin | rawimage | permissions)*>
<!ELEMENT properties (property)+>
<!ELEMENT property EMPTY>
<!-- If callout is specified, it must be a defined native function -->
<!--  with the signature: char* foo(void) -->
<!ATTLIST property
        Key      CDATA                          #REQUIRED
        Value    CDATA                          #REQUIRED
        Scope    (system | internal)            "internal"
        Callout  CDATA                          #IMPLIED
        Comment  CDATA                          #IMPLIED
>

<!ELEMENT localized_strings (localized_string)*>
    
<!-- 
    KeysClass: name of constants class that provides keys values.   
 -->
<!ATTLIST localized_strings
    Package     CDATA                           #REQUIRED
    Name        CDATA                           #REQUIRED
    KeysClass   CDATA                           #REQUIRED 
    Scope       (protected | public)            "public"
    Comment     CDATA                           #IMPLIED
>
<!ELEMENT localized_string EMPTY>
<!ATTLIST localized_string
        Key         CDATA                   #REQUIRED
        KeyValue    CDATA                   #IMPLIED
        Value       CDATA                   #REQUIRED
>

<!ELEMENT constants (constant_class)*>
<!ELEMENT constant_class (constant)*>

<!--
    KeysValuesProvider: does this class provide keys values.
    
    AutoValue: automatically generate integer values for constants
    (starting from zero and going up).

    JavaOnly: generate only .java file for constants.
    NativeOnly: generate only native definitions for constants.
-->
<!ATTLIST constant_class
    Package  CDATA                          #REQUIRED
    Name     CDATA                          #REQUIRED
    Scope    (protected | public)           "public"
    Comment  CDATA                          #IMPLIED
    KeysValuesProvider (true | false)       "false"
    AutoValue  (true | false)               "false"
    JavaOnly   (true | false)               "false"
    NativeOnly (true | false)               "false"
>

<!ELEMENT constant EMPTY>
<!ATTLIST constant
    Type      (int | String | boolean)       #IMPLIED
    Name      CDATA                          #REQUIRED
    Value     CDATA                          #IMPLIED
    VScope    (protected | public | private) "public"
    Comment   CDATA                          #IMPLIED
    JavaOnly   (true | false)                "false"
    NativeOnly (true | false)                "false"
>

<!--
    Top level node for skin description
-->
<!ELEMENT skin (skin_properties)>


<!--
    Skin properties description
-->
<!ELEMENT skin_properties (integer | integer_seq | string | font | 
        image | composite_image)+>
<!ATTLIST skin_properties
    KeysClass   CDATA                           #REQUIRED 
>

<!--
    Integer valued skin property
-->
<!ELEMENT integer EMPTY>
<!ATTLIST integer
        Key         CDATA                   #REQUIRED
        KeyValue    CDATA                   #IMPLIED
        Value       CDATA                   #REQUIRED
>

<!--
    Integers sequence valued skin property
-->
<!ELEMENT integer_seq EMPTY>
<!ATTLIST integer_seq
        Key         CDATA                   #REQUIRED
        KeyValue    CDATA                   #IMPLIED
        Value       CDATA                   #REQUIRED
>

<!--
    String valued skin property
-->
<!ELEMENT string EMPTY>
<!ATTLIST string
        Key         CDATA                   #REQUIRED
        KeyValue    CDATA                   #IMPLIED
        Value       CDATA                   #REQUIRED
>

<!--
    Font valued skin property
-->
<!ELEMENT font EMPTY>
<!ATTLIST font
        Key         CDATA                   #REQUIRED
        KeyValue    CDATA                   #IMPLIED
        Value       CDATA                   #REQUIRED
>

<!--
    Image valued skin property
-->
<!ELEMENT image EMPTY>
<!ATTLIST image
        Key         CDATA                   #REQUIRED
        KeyValue    CDATA                   #IMPLIED
        Value       CDATA                   #REQUIRED
        Romized     (true | false)          "false"
>

<!--
    Composite image valued skin property
-->
<!ELEMENT composite_image EMPTY>
<!ATTLIST composite_image
        Key         CDATA                   #REQUIRED
        KeyValue    CDATA                   #IMPLIED
        Value       CDATA                   #REQUIRED
        Pieces      CDATA                   #REQUIRED
        Romized     (true | false)          "false"
>

<!--
    Raw image format description
-->
<!ELEMENT rawimage EMPTY>
<!ATTLIST rawimage
        Format    (Putpixel | ARGB)         #REQUIRED
        Colors    (565 | 888)               #REQUIRED
        Endian    (Little | Big)            #REQUIRED
>

<!--
    Extended permissions description
-->
<!ELEMENT permissions (group)*>
<!ELEMENT group (permission)*>
<!ATTLIST group
        ID          CDATA                   #REQUIRED
>
<!ELEMENT permission EMPTY>
<!ATTLIST permission
        ID          CDATA                   #REQUIRED
        Name        CDATA                   #REQUIRED
>

=== vadosnaprimer/pspkvm/branches/virtual-keyboard/midp/src/configuration/configuration_xml/armsd/constants_open.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "../share/configuration.dtd">
<!--

        Copyright  1990-2007 Sun Microsystems, Inc. All Rights Reserved.
        DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
        
        This program is free software; you can redistribute it and/or
        modify it under the terms of the GNU General Public License version
        2 only, as published by the Free Software Foundation.
        
        This program is distributed in the hope that it will be useful, but
        WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
        General Public License version 2 for more details (a copy is
        included at /legal/license.txt).
        
        You should have received a copy of the GNU General Public License
        version 2 along with this work; if not, write to the Free Software
        Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
        02110-1301 USA
        
        Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa
        Clara, CA 95054 or visit www.sun.com if you need additional
        information or have any questions.

-->
<configuration>
<constants>
<constant_class Package="com.sun.midp.configurator" Name="Constants" Scope="public">
  <constant Type="int"
            Name="MAX_ISOLATES"
            Value="4"
            Comment="MAX_ISOLATES"/>

  <constant Type="int"
            Name="SUITE_MEMORY_RESERVED"
            Value="100"
            Comment="Default MIDletSuite memory reserved."/>
  <constant Type="int"
            Name="SUITE_MEMORY_LIMIT"
            Value="-1"
            Comment="Default MIDletSuite Memory Limit."/>

  <constant Type="int"
            Name="TCP_CLI_GLOBAL_LIMIT"
            Value="16"
            Comment="Global resource limit for TCP client sockets"/>
  <constant Type="int"
            Name="TCP_CLI_AMS_RESERVED"
            Value="2"
            Comment="Per suite resource limit for TCP client sockets"/>
  <constant Type="int"
            Name="TCP_CLI_AMS_LIMIT"
            Value="(TCP_CLI_GLOBAL_LIMIT)"
            Comment="Per suite resource limit for TCP client sockets"/>
  <constant Type="int"
            Name="TCP_CLI_SUITE_RESERVED"
            Value="0"
            Comment="Per suite resource limit for TCP client sockets"/>
  <constant Type="int"
            Name="TCP_CLI_SUITE_LIMIT"
            Value="(TCP_CLI_GLOBAL_LIMIT - TCP_CLI_AMS_RESERVED)"
            Comment="Per suite resource limit for TCP client sockets"/>

  <constant Type="int"
            Name="TCP_SER_GLOBAL_LIMIT"
            Value="12"
            Comment="Global resource limit for TCP server sockets"/>
  <constant Type="int"
            Name="TCP_SER_AMS_RESERVED"
            Value="0"
            Comment="Per suite resource limit for TCP server sockets"/>
  <constant Type="int"
            Name="TCP_SER_AMS_LIMIT"
            Value="(TCP_SER_GLOBAL_LIMIT)"
            Comment="Per suite resource limit for TCP server sockets"/>
  <constant Type="int"
            Name="TCP_SER_SUITE_RESERVED"
            Value="0"
            Comment="Per suite resource limit for TCP server sockets"/>
  <constant Type="int"
            Name="TCP_SER_SUITE_LIMIT"
            Value="(TCP_SER_GLOBAL_LIMIT - TCP_SER_AMS_RESERVED)"
            Comment="Per suite resource limit for TCP server sockets"/>

  <constant Type="int"
            Name="UDP_GLOBAL_LIMIT"
            Value="12"
            Comment="Global resource limit for UDP sockets"/>
  <constant Type="int"
            Name="UDP_AMS_RESERVED"
            Value="0"
            Comment="Per suite resource limit for UDP sockets"/>
  <constant Type="int"
            Name="UDP_AMS_LIMIT"
            Value="(UDP_GLOBAL_LIMIT)"
            Comment="Per suite resource limit for UDP sockets"/>
  <constant Type="int"
            Name="UDP_SUITE_RESERVED"
            Value="0"
            Comment="Per suite resource limit for UDP sockets"/>
  <constant Type="int"
            Name="UDP_SUITE_LIMIT"
            Value="(UDP_GLOBAL_LIMIT - UDP_AMS_RESERVED)"
            Comment="Per suite resource limit for UDP sockets"/>

  <constant Type="int"
            Name="FILE_GLOBAL_LIMIT"
            Value="30"
            Comment="Global resource limit for File handlers"/>
  <constant Type="int"
            Name="FILE_AMS_RESERVED"
            Value="6"
            Comment="Per suite resource limit for File handlers"/>
  <constant Type="int"
            Name="FILE_AMS_LIMIT"
            Value="(FILE_GLOBAL_LIMIT)"
            Comment="Per suite resource limit for File handlers"/>
  <constant Type="int"
            Name="FILE_SUITE_RESERVED"
            Value="4"
            Comment="Per suite resource limit for File handlers"/>
  <constant Type="int"
            Name="FILE_SUITE_LIMIT"
            Value="(FILE_GLOBAL_LIMIT - FILE_AMS_RESERVED)"
            Comment="Per suite resource limit for File handlers"/>

  <constant Type="int"
            Name="AUDIO_CHA_GLOBAL_LIMIT"
            Value="5"
            Comment="Global resource limit for Audio channels"/>
  <constant Type="int"
            Name="AUDIO_CHA_AMS_RESERVED"
            Value="0"
            Comment="Per suite resource limit for Audio channels"/>
  <constant Type="int"
            Name="AUDIO_CHA_AMS_LIMIT"
            Value="(AUDIO_CHA_GLOBAL_LIMIT)"
            Comment="Per suite resource limit for Audio channels"/>
  <constant Type="int"
            Name="AUDIO_CHA_SUITE_RESERVED"
            Value="0"
            Comment="Per suite resource limit for Audio channels"/>
  <constant Type="int"
            Name="AUDIO_CHA_SUITE_LIMIT"
            Value="(AUDIO_CHA_GLOBAL_LIMIT - AUDIO_CHA_AMS_RESERVED)"
            Comment="Per suite resource limit for Audio channels"/>

  <constant Type="int"
            Name="IMAGE_MUT_GLOBAL_LIMIT"
            Value="1200000"
            Comment="Global resource limit for mutable images"/>
  <constant Type="int"
            Name="IMAGE_MUT_AMS_RESERVED"
            Value="200000"
            Comment="Per suite resource limit for mutable images"/>
  <constant Type="int"
            Name="IMAGE_MUT_AMS_LIMIT"
            Value="(IMAGE_MUT_GLOBAL_LIMIT)"
            Comment="Per suite resource limit for mutable images"/>
  <constant Type="int"
            Name="IMAGE_MUT_SUITE_RESERVED"
            Value="0"
            Comment="Per suite resource limit for mutable images"/>
  <constant Type="int"
            Name="IMAGE_MUT_SUITE_LIMIT"
            Value="(IMAGE_MUT_GLOBAL_LIMIT - IMAGE_MUT_AMS_RESERVED)"
            Comment="Per suite resource limit for mutable images"/>

  <constant Type="int"
            Name="IMAGE_IMMUT_GLOBAL_LIMIT"
            Value="1300000"
            Comment="Global resource limit for immutable images"/>
  <constant Type="int"
            Name="IMAGE_IMMUT_AMS_RESERVED"
            Value="700000"
            Comment="Per suite resource limit for immutable images"/>
  <constant Type="int"
            Name="IMAGE_IMMUT_AMS_LIMIT"
            Value="(IMAGE_IMMUT_GLOBAL_LIMIT)"
            Comment="Per suite resource limit for immutable images"/>
  <constant Type="int"
            Name="IMAGE_IMMUT_SUITE_RESERVED"
            Value="0"
            Comment="Per suite resource limit for immutable images"/>
  <constant Type="int"
            Name="IMAGE_IMMUT_SUITE_LIMIT"
            Value="(IMAGE_IMMUT_GLOBAL_LIMIT - IMAGE_IMMUT_AMS_RESERVED)"
            Comment="Per suite resource limit for immutable images"/>
 </constant_class>
</constants>
</configuration>

=== vadosnaprimer/pspkvm/tags/pspkvm-v0_3_0-20080331/midp/src/configuration/configuration_xml/share/ams/suitestore_constants.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "../configuration.dtd">
<!--


        Copyright  1990-2007 Sun Microsystems, Inc. All Rights Reserved.
        DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
        
        This program is free software; you can redistribute it and/or
        modify it under the terms of the GNU General Public License version
        2 only, as published by the Free Software Foundation.
        
        This program is distributed in the hope that it will be useful, but
        WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
        General Public License version 2 for more details (a copy is
        included at /legal/license.txt).
        
        You should have received a copy of the GNU General Public License
        version 2 along with this work; if not, write to the Free Software
        Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
        02110-1301 USA
        
        Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa
        Clara, CA 95054 or visit www.sun.com if you need additional
        information or have any questions.
-->

<configuration>
<constants>

<!--
    Indentifiers for Suite Storage subsystem
-->
<constant_class Package="com.sun.midp.configurator" Name="Constants" Scope="public"
    Comment="/** Indentifiers for the Suite Storage subsystem */">
 <constant Type="String"
            Name="SETTINGS_FILENAME"
            Value=".ss"
            NativeOnly="true"
            Comment="Extension of the file to save suites settings."/>
 <constant Type="String"
            Name="INSTALL_INFO_FILENAME"
            Value=".ii"
            NativeOnly="true"
            Comment="Extension of the file to save the suite installation information."/>
 <constant Type="String"
            Name="PROPS_FILENAME"
            Value=".ap"
            NativeOnly="true"
            Comment="Extension of the file to save the suite application properties."/>
 <constant Type="String"
            Name="SECURE_EXTENSION"
            Value=".ssr"
            NativeOnly="true"
            Comment="Extension of the file to save the suite secure resources."/>
 <constant Type="String"
            Name="TMP_EXT"
            Value=".tmp"
            NativeOnly="true"
            Comment="Temporary file extension."/>
 <constant Type="String"
            Name="IDX_EXTENSION"
            Value=".idx"
            NativeOnly="true"
            Comment="RMS index file extension."/>
 <constant Type="String"
            Name="DB_EXTENSION"
            Value=".db"
            NativeOnly="true"
            Comment="RMS database file extension."/>
 <constant Type="String"
            Name="JAR_EXTENSION"
            Value=".jar"
            NativeOnly="true"
            Comment="Suite's JAR file extension."/>
 <constant Type="String"
            Name="TRANSACTION_DATA_FILENAME"
            Value="_trans.dat"
            NativeOnly="true"
            Comment="Name of the file containing information about the current transaction."/>
 <constant Type="String"
            Name="SUITE_DATA_FILENAME"
            Value="_suites.dat"
            NativeOnly="true"
            Comment="Name of the file with the basic information about the installed suites."/>
 <constant Type="String"
            Name="ICON_CACHE_FILENAME"
            Value="_icons.dat"
            NativeOnly="true"
            Comment="Name of the file with the cached icons."/>
 <constant Type="String"
            Name="INSTALL_NOTIFY_PROP"
            Value="MIDlet-Install-Notify"
            NativeOnly="true"
            Comment="MIDlet property for the install notify URL."/>
 <constant Type="String"
            Name="DELETE_NOTIFY_PROP"
            Value="MIDlet-Delete-Notify"
            NativeOnly="true"
            Comment="MIDlet property for the delete notify URL."/>
 <constant Type="String"
            Name="SUITE_NAME_PROP"
            Value="MIDlet-Name"
            NativeOnly="true"
            Comment="MIDlet property for the suite name."/>
 <constant Type="String"
            Name="SUITE_VENDOR_PROP"
            Value="MIDlet-Name"
            NativeOnly="true"
            Comment="MIDlet property for the suite vendor."/>
 <constant Type="String"
            Name="SUITE_VERSION_PROP"
            Value="MIDlet-Version"
            NativeOnly="true"
            Comment="MIDlet property for the suite version."/>
 <constant Type="String"
            Name="SUITE_DESC_PROP"
            Value="MIDlet-Description"
            NativeOnly="true"
            Comment="MIDlet property for the suite description."/>
</constant_class>

</constants>
</configuration>

=== vadosnaprimer/pspkvm/branches/transformers/midp/src/configuration/configuration_xml/linux_gci/constants.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "../share/configuration.dtd">
<!--
          

        Copyright  1990-2007 Sun Microsystems, Inc. All Rights Reserved.
        DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
        
        This program is free software; you can redistribute it and/or
        modify it under the terms of the GNU General Public License version
        2 only, as published by the Free Software Foundation.
        
        This program is distributed in the hope that it will be useful, but
        WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
        General Public License version 2 for more details (a copy is
        included at /legal/license.txt).
        
        You should have received a copy of the GNU General Public License
        version 2 along with this work; if not, write to the Free Software
        Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
        02110-1301 USA
        
        Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa
        Clara, CA 95054 or visit www.sun.com if you need additional
        information or have any questions.
-->
<configuration>
<constants>
<constant_class Package="com.sun.midp.configurator" Name="Constants" Scope="public">
  <constant Type="int"
            Name="IMAGE_CACHE_THRESHOLD"
            Value="(100*1024)"
            Comment="Threshold for image cache storage"/>
  <constant Type="boolean"
            Name="PORTING_NO_FILESYSTEM"
            Value="false"
            Comment="Whether your platform supports File System. Set to true when File System is not supported; set to false when File System is supported."/>
<!-- Package javax.microedition.lcdui.game -->
  <constant Type="int"
            Name="GAMECANVAS_FULLWIDTH"
            Value="176"
            Comment="(Fixed) full display width"/>
  <constant Type="int"
            Name="GAMECANVAS_FULLHEIGHT"
            Value="210"
            Comment="(Fixed) full display height"/>

<!-- Package javax.microedition.lcdui -->
  <constant Type="boolean"
            Name="CHAM_USE_IMAGES"
            Value="true"
            Comment="When false, Chameleon will not even attempt to load images for the UI."/>
  <constant Type="boolean"
            Name="CHAM_ROMIZED_IMAGES"
            Value="false"
            Comment="When false, Chameleon will not even attempt to load romized images for the UI."/>
  <constant Type="int"
            Name="CHAM_WIDTH"
            Value="176"
            Comment="(Chameleon Only) display width"/>
  <constant Type="int"
            Name="CHAM_FULLWIDTH"
            Value="176"
            Comment="(Chameleon Only) full display width"/>
  <constant Type="int"
            Name="CHAM_HEIGHT"
            Value="210"
            Comment="(Chameleon Only) display height"/>
  <constant Type="int"
            Name="CHAM_FULLHEIGHT"
            Value="210"
            Comment="(Chameleon Only) full display height"/>
  <constant Type="boolean"
            Name="TRAVERSAL2D"
            Value="true"
            Comment="(Chameleon Only) 2-D Traversal flag"/>            
  <constant Type="int"
            Name="MAX_EVENTS"
            Value="20"
            Comment="The maximum number of events in the event queue"/>
  <constant Type="int"
            Name="FULLWIDTH"
            Value="176"
            Comment="(Fixed) full display width"/>
  <constant Type="int"
            Name="FULLHEIGHT"
            Value="210" 
            Comment="(Fixed) full display height"/>
  <constant Type="int"
            Name="NORMALWIDTH"
            Value="176" 
            Comment="(Fixed) normal width"/>
  <constant Type="int"
            Name="NORMALHEIGHT"
            Value="210" 
            Comment="(Fixed) normal height"/>
  <constant Type="int"
            Name="VERT_SCROLLBAR_WIDTH"
            Value="16" 
            Comment="the width of the vertical scrollbar"/>
  <constant Type="int"
            Name="ERASE_COLOR"
            Value="0x00FFFFFF" 
            Comment="Color, in hex, to use as the erase color (the color used to clear away any existing pixels from a graphics object before painting the new pixels)."/>
  <constant Type="boolean"
            Name="SCROLLS_HORIZONTAL"
            Value="false"
            Comment="Whether the viewport is capable of scrolling horizontally"/>
  <constant Type="boolean"
            Name="SCROLLS_VERTICAL"
            Value="true"
            Comment="Whether the viewport is capable of scrolling vertically"/>
  <constant Type="int"
            Name="DISPLAY_DEPTH"
            Value="16" 
            Comment="Color depth the platform supports, in bits per pixel (bpp)."/>
  <constant Type="int"
            Name="IMAGE_DEPTH"
            Value="32" 
            Comment="Depth of the platform image (in bits). @note This is the bit depth of an image and it may not be the same as the bit depth of the entire system."/>
  <constant Type="boolean"
            Name="DISPLAY_IS_COLOR"
            Value="true" 
            Comment="Whether the platform supports color: set it to true when color is supported; set it to false when color is not supported."/>
  <constant Type="int"
            Name="DISPLAY_NUM_COLOR"
            Value="65536" 
            Comment="Number of color the platform supports"/>
  <constant Type="int"
            Name="ALPHA_LEVELS"
            Value="256" 
            Comment="Number of alpha channel levels the platform supports"/>
  <constant Type="boolean"
            Name="IS_DOUBLE_BUFFERED"
            Value="true" 
            Comment="Whether the platform and MIDP implementation supports double-buffering: set to true when double-buffering is supported; set to false when double-buffering is not supported."/>
  <constant Type="int"
            Name="KEYCODE_UP"
            Value="-1" 
            Comment="key up code (internal)"/>
  <constant Type="int"
            Name="KEYCODE_DOWN"
            Value="-2" 
            Comment="key down code (internal)"/>
  <constant Type="int"
            Name="KEYCODE_LEFT"
            Value="-3" 
            Comment="key left code (internal)"/>
  <constant Type="int"
            Name="KEYCODE_RIGHT"
            Value="-4" 
            Comment="key right code (internal)"/>
  <constant Type="int"
            Name="KEYCODE_SELECT"
            Value="-5" 
            Comment="key select code (internal)"/>
  <constant Type="boolean"
            Name="MEASURE_STARTUP"
            Value="false" 
            Comment="Turn on/off startup time measurement printouts."/>
  <constant Type="boolean"
            Name="POINTER_SUPPORTED"
            Value="true" 
            Comment="Whether both the platform and MIDP implementation provide support for a pointer (press and release). Set to true when pointer is supported; set to false when pointer is not supported."/>
  <constant Type="boolean"
            Name="MOTION_SUPPORTED"
            Value="true" 
            Comment="If your platform supports pointer motion and you want MIDP implementation provides support for pointer motions, set it to true; otherwise, set it to false so that MIDP runtime can provide this information to MIDlet."/>
  <constant Type="boolean"
            Name="REPEAT_SUPPORTED"
            Value="false" 
            Comment="If your platform support key repeat and you want MIDP implementation provides support for key repeat, set this to true, otherwise set it to false."/>
<!-- Memory limits -->
  <constant Type="int"
            Name="JAVA_HEAP_CAPACITY_SVM"
            Value="1024" 
            Comment="Java heap capacity in SVM mode"/>
  <constant Type="int"
            Name="JAVA_HEAP_CAPACITY_MVM"
            Value="(4*1024)" 
            Comment="Java heap capacity in MVM mode"/>
 </constant_class>
<!-- Package com.sun.midp.rms -->
<constant_class Package="com.sun.midp.rms" Name="RMSConfig" Scope="public" Comment="/** Constant values in RMS configuration */">
  <constant Type="int"
            Name="STORAGE_SUITE_LIMIT"
            Value="200000"
            Comment="Per suite resource limit for storage"/>
  <constant Type="int"
            Name="RMS_CACHE_LIMIT"
            Value="3072"
            Comment="Global memory limit (in Bytes) for RMS caching"/>
 </constant_class>
</constants>
</configuration>
