=== vadosnaprimer/pspkvm/pspkvm-v0_3_1-20080408/midp/src/configuration/configuration_xml/share/configuration.dtd
<!--
        	

        Copyright  1990-2007 Sun Microsystems, Inc. All Rights Reserved.
        DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
        
        This program is free software; you can redistribute it and/or
        modify it under the terms of the GNU General Public License version
        2 only, as published by the Free Software Foundation.
        
        This program is distributed in the hope that it will be useful, but
        WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
        General Public License version 2 for more details (a copy is
        included at /legal/license.txt).
        
        You should have received a copy of the GNU General Public License
        version 2 along with this work; if not, write to the Free Software
        Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
        02110-1301 USA
        
        Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa
        Clara, CA 95054 or visit www.sun.com if you need additional
        information or have any questions.
-->
<!ELEMENT configuration (properties | constants | localized_strings | skin | rawimage | permissions)*>
<!ELEMENT properties (property)+>
<!ELEMENT property EMPTY>
<!-- If callout is specified, it must be a defined native function -->
<!--  with the signature: char* foo(void) -->
<!ATTLIST property
        Key      CDATA                          #REQUIRED
        Value    CDATA                          #REQUIRED
        Scope    (system | internal)            "internal"
        Callout  CDATA                          #IMPLIED
        Comment  CDATA                          #IMPLIED
>

<!ELEMENT localized_strings (localized_string)*>
    
<!-- 
    KeysClass: name of constants class that provides keys values.   
 -->
<!ATTLIST localized_strings
    Package     CDATA                           #REQUIRED
    Name        CDATA                           #REQUIRED
    KeysClass   CDATA                           #REQUIRED 
    Scope       (protected | public)            "public"
    Comment     CDATA                           #IMPLIED
>
<!ELEMENT localized_string EMPTY>
<!ATTLIST localized_string
        Key         CDATA                   #REQUIRED
        KeyValue    CDATA                   #IMPLIED
        Value       CDATA                   #REQUIRED
>

<!ELEMENT constants (constant_class)*>
<!ELEMENT constant_class (constant)*>

<!--
    KeysValuesProvider: does this class provide keys values.
    
    AutoValue: automatically generate integer values for constants
    (starting from zero and going up).

    JavaOnly: generate only .java file for constants.
    NativeOnly: generate only native definitions for constants.
-->
<!ATTLIST constant_class
    Package  CDATA                          #REQUIRED
    Name     CDATA                          #REQUIRED
    Scope    (protected | public)           "public"
    Comment  CDATA                          #IMPLIED
    KeysValuesProvider (true | false)       "false"
    AutoValue  (true | false)               "false"
    JavaOnly   (true | false)               "false"
    NativeOnly (true | false)               "false"
>

<!ELEMENT constant EMPTY>
<!ATTLIST constant
    Type      (int | String | boolean)       #IMPLIED
    Name      CDATA                          #REQUIRED
    Value     CDATA                          #IMPLIED
    VScope    (protected | public | private) "public"
    Comment   CDATA                          #IMPLIED
    JavaOnly   (true | false)                "false"
    NativeOnly (true | false)                "false"
>

<!--
    Top level node for skin description
-->
<!ELEMENT skin (skin_properties)>


<!--
    Skin properties description
-->
<!ELEMENT skin_properties (integer | integer_seq | string | font | 
        image | composite_image)+>
<!ATTLIST skin_properties
    KeysClass   CDATA                           #REQUIRED 
>

<!--
    Integer valued skin property
-->
<!ELEMENT integer EMPTY>
<!ATTLIST integer
        Key         CDATA                   #REQUIRED
        KeyValue    CDATA                   #IMPLIED
        Value       CDATA                   #REQUIRED
>

<!--
    Integers sequence valued skin property
-->
<!ELEMENT integer_seq EMPTY>
<!ATTLIST integer_seq
        Key         CDATA                   #REQUIRED
        KeyValue    CDATA                   #IMPLIED
        Value       CDATA                   #REQUIRED
>

<!--
    String valued skin property
-->
<!ELEMENT string EMPTY>
<!ATTLIST string
        Key         CDATA                   #REQUIRED
        KeyValue    CDATA                   #IMPLIED
        Value       CDATA                   #REQUIRED
>

<!--
    Font valued skin property
-->
<!ELEMENT font EMPTY>
<!ATTLIST font
        Key         CDATA                   #REQUIRED
        KeyValue    CDATA                   #IMPLIED
        Value       CDATA                   #REQUIRED
>

<!--
    Image valued skin property
-->
<!ELEMENT image EMPTY>
<!ATTLIST image
        Key         CDATA                   #REQUIRED
        KeyValue    CDATA                   #IMPLIED
        Value       CDATA                   #REQUIRED
        Romized     (true | false)          "false"
>

<!--
    Composite image valued skin property
-->
<!ELEMENT composite_image EMPTY>
<!ATTLIST composite_image
        Key         CDATA                   #REQUIRED
        KeyValue    CDATA                   #IMPLIED
        Value       CDATA                   #REQUIRED
        Pieces      CDATA                   #REQUIRED
        Romized     (true | false)          "false"
>

<!--
    Raw image format description
-->
<!ELEMENT rawimage EMPTY>
<!ATTLIST rawimage
        Format    (Putpixel | ARGB)         #REQUIRED
        Colors    (565 | 888)               #REQUIRED
        Endian    (Little | Big)            #REQUIRED
>

<!--
    Extended permissions description
-->
<!ELEMENT permissions (group)*>
<!ELEMENT group (permission)*>
<!ATTLIST group
        ID          CDATA                   #REQUIRED
>
<!ELEMENT permission EMPTY>
<!ATTLIST permission
        ID          CDATA                   #REQUIRED
        Name        CDATA                   #REQUIRED
>

=== vadosnaprimer/pspkvm/tags/pspkvm-v0_3_2-20080427/jsr135/src/config/javacall/properties_jsr135.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "configuration.dtd">
<!--
        Copyright  1990-2007 Sun Microsystems, Inc. All Rights Reserved.
        DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
        
        This program is free software; you can redistribute it and/or
        modify it under the terms of the GNU General Public License version
        2 only, as published by the Free Software Foundation.
        
        This program is distributed in the hope that it will be useful, but
        WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
        General Public License version 2 for more details (a copy is
        included at /legal/license.txt).
        
        You should have received a copy of the GNU General Public License
        version 2 along with this work; if not, write to the Free Software
        Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
        02110-1301 USA
        
        Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa
        Clara, CA 95054 or visit www.sun.com if you need additional
        information or have any questions.
-->
<!-- MMAPI PROPERTIES required by the specification -->
<configuration>
<properties>
<!-- SYSTEM PROPERTIES -->
<!-- Visible from System.getProperty() -->
    <!-- JSR135(MMAPI) PROPERTIES -->
    <property Key="microedition.media.version"
      Value="1.1"
      Scope="system"
      Comment="Version number."/>

    <property Key="supports.mixing"
      Value=""
      Scope="system"
      Callout="get_system_property_supports_mixing" 
      Comment="Mixing support."/>

    <property Key="supports.audio.capture"
      Value="true"
      Scope="system"
      Comment="Audio capture support."/>

    <property Key="supports.video.capture"
      Value="false"
      Scope="system"
      Comment="Video capture support."/>

    <property Key="supports.recording"
      Value="true"
      Scope="system"
      Comment="Recording support."/>

    <property Key="audio.encodings" 
      Value="encoding=pcm" 
	  Scope="system"/>

    <!--
    <property Key="audio.encodings"
      Value="encoding=pcm encoding=pcm&amp;rate=8000&amp;bits=8&amp;channels=1 encoding=pcm&amp;rate=22050&amp;bits=16&amp;channels=2"
      Scope="system"
      Comment="Supported audio encodings."/>

    <property Key="video.encodings"
      Value="encoding=png"
      Scope="system"
      Comment="Supported video encodings."/>
    -->

    <!--
    <property Key="video.encodings"
      Value="encoding=rgb565&amp;width=160&amp;height=120 encoding=rgb565&amp;width=320&amp;height=240 encoding=rgb565&amp;width=120&amp;height=160"
      Scope="system"
      Comment="Supported video encodings."/>
    -->

    <property Key="video.snapshot.encodings"
      Value=""
      Scope="system"
      Comment="Supported video snapshot encodings."/>

    <!--
    <property Key="video.snapshot.encodings"
      Value="encoding=jpeg encoding=png"
      Scope="system"
      Comment="Supported video snapshot encodings."/>
    -->

    <!--
    <property Key="streamable.contents"
      Value="audio/x-wav"
      Scope="system"
      Comment="Streamable contents."/>
    -->

</properties>
</configuration>

=== vadosnaprimer/pspkvm/branches/virtual-keyboard/midp/src/configuration/configuration_xml/share/properties.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "./configuration.dtd">
<!--
		  

		Copyright  1990-2007 Sun Microsystems, Inc. All Rights Reserved.
		DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
		
		This program is free software; you can redistribute it and/or
		modify it under the terms of the GNU General Public License version
		2 only, as published by the Free Software Foundation.
		
		This program is distributed in the hope that it will be useful, but
		WITHOUT ANY WARRANTY; without even the implied warranty of
		MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
		General Public License version 2 for more details (a copy is
		included at /legal/license.txt).
		
		You should have received a copy of the GNU General Public License
		version 2 along with this work; if not, write to the Free Software
		Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
		02110-1301 USA
		
		Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa
		Clara, CA 95054 or visit www.sun.com if you need additional
		information or have any questions.
-->
<!-- Properties file common for all platforms -->
<configuration>
<properties>
<!-- INTERNAL PROPERTIES -->
<!-- Visible from Configuration.getProperty() -->
  <!-- System tunable parameters -->

  <property Key="destroyMIDletTimeout"
	  Value="5000"
	  Scope="internal"
	  Comment="Timeout in milliseconds to destroy a running MIDlet"/>

  <property Key="suspendAppTimeout"
	  Value="2000"
	  Scope="internal"
	  Comment="Timeout in milliseconds for MIDlets to complete 
                   pauseApp() execution within java stack pause"/>

  <property Key="suspendAlertTime"
      Value="900"
      Scope="internal"
      Comment="Time in milliseconds for minimal duration of java suspension.
        It is required to let a user see alert of java suspending. If the
        time is too short, the alert will not be not shown possibly. If set
        to 0 the alert will not be shown definitely."/>

  <property Key="system.jam_space"
	  Value="1000000"
	  Scope="internal"
	  Comment="Amount of space to reserve for JAM storage."/>

  <property Key="system.i18n.lang"
	  Value="en"
	  Scope="internal"
	  Comment="Default language for I18N processing."/>      
  <property Key="system.i18n.encoding"
	  Value="ISO8859_1"
	  Scope="internal"
	  Comment="Default encoding for I18N processing."/>
      
  <!-- serial port buffering is on by default to support available() -->
  <property Key="com.sun.midp.io.j2me.comm.buffersize"
				Value="256"
				Scope="internal"/>

  <!-- TCP buffering is off by default -->
  <!-- property Key="com.sun.midp.io.j2me.socket.buffersize"
				Value="0"
				Scope="internal"/> -->

  <property Key="com.sun.midp.lcdui.eventHandler"
	  Value="com.sun.midp.lcdui.DefaultEventHandler"
	  Scope="internal"
	  Comment="Default event handler class."/>
  <property Key="com.sun.midp.lcdui.inputHandler"
	  Value="com.sun.midp.lcdui.DefaultInputMethodHandler"
	  Scope="internal"
	  Comment="Default input handler class."/>

  <!-- property Key="com.sun.midp.io.http.proxy" 
				Value="webcache:8080" 
				Scope="internal"/ -->
  <!-- property Key="com.sun.midp.io.http.force_non_persistent" 
				Value="false" 
				Scope="internal"/ -->
  <!-- property Key="com.sun.midp.io.http.persistent_connection_linger_time" 
				Value="60000" 
				Scope="internal"/ -->
  <!-- property Key="com.sun.midp.io.http.input_buffer_size" 
				Value="256" 
				Scope="internal"/ -->
  <!-- property Key="com.sun.midp.io.http.output_buffer_size" 
				Value="2048" 
				Scope="internal"/ -->
  <!-- property Key="com.sun.midp.io.http.max_persistent_connections" 
				Value="4" 
				Scope="internal"/ -->

  <!-- Event queue dispatch table tuning -->
  <!-- property Key="com.sun.midp.events.dispatchTableInitSize" 
				Value="16" 
				Scope="internal"/ -->
      
  <property Key="VmDebuggerPort"
	  Value="2808"
	  Scope="internal"
	  Comment="VM debugger port number."/>
      
      
  <property Key="DisableStartupErrorAlert"
	  Value="0"
	  Scope="internal"
	  Comment="If not 0, don't display start up errors in a
                  Java Alert."/>
      
  <!-- Parser class names for push supported protocols -->
  <property Key="btl2cap"
	    Value="com.sun.midp.jsr82.ProtocolPushImpl"
	    Scope="internal"/>				
  <property Key="btspp"
	    Value="com.sun.midp.jsr82.ProtocolPushImpl"
	    Scope="internal"/>				
  <property Key="btgoep"
	    Value="com.sun.midp.jsr82.ProtocolPushImpl"
	    Scope="internal"/>				
  <property Key="socket"
	    Value="com.sun.midp.io.j2me.socket.ProtocolPushImpl"
	    Scope="internal"/>				
  <property Key="datagram"
	    Value="com.sun.midp.io.j2me.datagram.ProtocolPushImpl"
	    Scope="internal"/>				
  <property Key="sip"
	    Value="gov.nist.core.ProtocolPushImpl"
	    Scope="internal"/>				
  <property Key="sips"
	    Value="gov.nist.core.ProtocolPushImpl"
	    Scope="internal"/>				
  <property Key="sms"
	    Value="com.sun.midp.wma.ProtocolPushImpl"
	    Scope="internal"/>				
  <property Key="cbs"
	    Value="com.sun.midp.wma.ProtocolPushImpl"
	    Scope="internal"/>				
  <property Key="mms"
	    Value="com.sun.midp.io.j2me.mms.ProtocolPushImpl"
	    Scope="internal"/>				
<!-- SYSTEM PROPERTIES -->
<!-- Visible from System.getProperty() -->

  <property Key="microedition.hostname" 
		Value="" 
		Scope="system"
		Callout="getLocalHostName"
		Comment="The local hostname."/>
  <property Key="microedition.configuration" 
		Value="CLDC-1.1" 
		Scope="system"
		Comment="Configuration information."/>
  <property Key="microedition.profiles" 
		Value="MIDP-2.1" 
		Scope="system"
		Comment="Profile information."/>
  <property Key="microedition.locale" 
		Value="en-US"
		Scope="system"
		Comment="System locale."/>
  <property Key="microedition.platform" 
		Value="j2me" 
		Scope="system"
		Comment="Platform name."/>
  <!-- property Key="microedition.encoding" 
		Value="ISO8859_1" 
		Scope="system"/ -->
  <property Key="microedition.commports" 
	    Value="COM1" 
		Scope="system"/>
  <property Key="microedition.jtwi.version" 
		Value="1.0" 
		Scope="system"
		Comment="JWTI version number."/>
  <property Key="microedition.msa.version"
                Value="1.0"
                Scope="system"
                Comment="Specification version number."/>

  <!-- CLDC implementation parameters -->
  <!-- use MIDP protocol implementations -->
  <property Key="javax.microedition.io.Connector.protocolpath" 
		Value="com.sun.midp.io"
		Scope="system"
		Comment=""/>
  <!-- property Key="java.lang.Character.caseConverter" 
		Value="com.sun.cldc.i18n.uclc.DefaultCaseConverter" 
		Scope="system"/ -->
  <!-- property Key="com.sun.cldc.i18n.Helper.i18npath" 
		Value="com.sun.cldc.i18n.j2me" 
		Scope="system"/ -->
  <!-- property Key="microedition.implpath"
		Value="com.sun.cldc" 
		Scope="system"/ -->
  <property Key="com.sun.cldc.util.j2me.TimeZoneImpl.timezone" 
		Value="" 
		Scope="system"
		Callout="getLocalTimeZone"
		Comment="System function of getting local time zone."/>
</properties>
</configuration>

=== vadosnaprimer/pspkvm/branches/jsr179/jsr179/src/config/common/properties_jsr179.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "configuration.dtd">
<!--
  
  
  Copyright  1990-2007 Sun Microsystems, Inc. All Rights Reserved.
  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
  
  This program is free software; you can redistribute it and/or
  modify it under the terms of the GNU General Public License version
  2 only, as published by the Free Software Foundation.
  
  This program is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  General Public License version 2 for more details (a copy is
  included at /legal/license.txt).
  
  You should have received a copy of the GNU General Public License
  version 2 along with this work; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
  02110-1301 USA
  
  Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa
  Clara, CA 95054 or visit www.sun.com if you need additional
  information or have any questions.
-->
<!-- System-independent JSR 179 properties required by the specification -->
<configuration>
<properties>
<!-- SYSTEM PROPERTIES -->
<!-- Visible from System.getProperty() -->
  <property Key="microedition.location.version"
      Value="1.0.1"
      Scope="system"
      Comment="Version number of the Location API"/>
<!-- INTERNAL PROPERTIES -->
<!-- Visible from Configuration.getProperty() -->
  <property Key="com.sun.j2me.location.OrientationSupported"
      Value="false"
      Scope="internal"
      Comment="True when orientation is supported, false otherwise."/>
  <property Key="com.sun.j2me.location.ProximitySupported"
      Value="true"
      Scope="internal"
      Comment="True when proximity monitoring is supported, false otherwise."/>
  <property Key="com.sun.j2me.location.CreateLandmarkStoreSupported"
      Value="true"
      Scope="internal"
      Comment="True when landmark store creation is supported, false otherwise."/>
  <property Key="com.sun.j2me.location.DeleteLandmarkStoreSupported"
      Value="true"
      Scope="internal"
      Comment="True when landmark store deletion is supported, false otherwise."/>
  <property Key="com.sun.j2me.location.DeleteCategorySupported"
      Value="true"
      Scope="internal"
      Comment="True when category deletion is supported, false otherwise."/>
  <property Key="com.sun.j2me.location.ResetTimeout"
      Value="10"
      Scope="internal"
      Comment="Timeout value in seconds for LocationProvider.reset() method."/>
</properties>
</configuration>

=== vadosnaprimer/pspkvm/trunk/jsr75/src/config/javacall/properties_jsr75.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="html.xsl"?>
<!DOCTYPE configuration SYSTEM "../common/configuration.dtd">
<!--
  
  Copyright  1990-2007 Sun Microsystems, Inc. All Rights Reserved.
  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
  
  This program is free software; you can redistribute it and/or
  modify it under the terms of the GNU General Public License version
  2 only, as published by the Free Software Foundation.
  
  This program is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  General Public License version 2 for more details (a copy is
  included at /legal/license.txt).
  
  You should have received a copy of the GNU General Public License
  version 2 along with this work; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
  02110-1301 USA
  
  Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa
  Clara, CA 95054 or visit www.sun.com if you need additional
  information or have any questions.
  
-->
<!-- System-independent JSR 75 properties required by the specification -->
<configuration>
<properties>
<!-- System  properties (visible via System.getProperty() -->
  <property Key="file.separator"
      Value=""
      Scope="system"
      Callout="getFileSeparator"
      Comment="The file separator character(s) for the underlying platform."/>

  <property Key="fileconn.dir.photos"
      Value=""
      Scope="system"
      Callout="getPhotosDir"
      Comment="The directory for photos and other images."/>

  <property Key="fileconn.dir.videos"
      Value=""
      Scope="system"
      Callout="getVideosDir"
      Comment="The directory for video clips."/>

  <property Key="fileconn.dir.graphics"
      Value=""
      Scope="system"
      Callout="getGraphicsDir"
      Comment="The directory for clip art graphics."/>

  <property Key="fileconn.dir.tones"
      Value=""
      Scope="system"
      Callout="getTonesDir"
      Comment="The directory for ring tones and other audio files."/>

  <property Key="fileconn.dir.music"
      Value=""
      Scope="system"
      Callout="getMusicDir"
      Comment="The directory for music."/>

  <property Key="fileconn.dir.recordings"
      Value=""
      Scope="system"
      Callout="getRecordingsDir"
      Comment="The directory for voice recordings."/>

  <property Key="fileconn.dir.private"
      Value=""
      Scope="system"
      Callout="getPrivateDir"
      Comment="The private work directory for MIDlet suite."/>

  <property Key="fileconn.dir.photos.name"
      Value=""
      Scope="system"
      Callout="getLocalizedPhotosDir"
      Comment="The localized name of photos and other images directory."/>

  <property Key="fileconn.dir.videos.name"
      Value=""
      Scope="system"
      Callout="getLocalizedVideosDir"
      Comment="The localized name of video clips directory."/>

  <property Key="fileconn.dir.graphics.name"
      Value=""
      Scope="system"
      Callout="getLocalizedGraphicsDir"
      Comment="The localized name of clip art graphics directory."/>

  <property Key="fileconn.dir.tones.name"
      Value=""
      Scope="system"
      Callout="getLocalizedTonesDir"
      Comment="The localized name of ring tones and other audio files directory."/>

  <property Key="fileconn.dir.music.name"
      Value=""
      Scope="system"
      Callout="getLocalizedMusicDir"
      Comment="The localized name of music directory."/>

  <property Key="fileconn.dir.recordings.name"
      Value=""
      Scope="system"
      Callout="getLocalizedRecordingsDir"
      Comment="The localized name of voice recordings directory."/>

  <property Key="fileconn.dir.private.name"
      Value=""
      Scope="system"
      Callout="getLocalizedPrivateDir"
      Comment="The localized name of private directory for MIDlet suite."/>

<!-- Internal properties (visible via Configuration.getProperty() -->
  <property Key="PIMRootDir"
      Value="file:///C:/"
      Scope="internal"
      Comment="The root directory that contains PIM data."/>
      
  <property Key="DefaultContactList"
      Value=""
      Scope="internal"
      Comment="The directory name of the default contact list."/> 

  <property Key="DefaultEventList"
      Value=""
      Scope="internal"
      Comment="The directory name of the default event list."/> 

  <property Key="DefaultTodoList"
      Value=""
      Scope="internal"
      Comment="The directory name of the default todo list."/> 

  <property Key="file.linebreak"
      Value="\r\n"
      Scope="internal"
      Comment="The which terminates a line in text files."/>
</properties>
</configuration>

=== vadosnaprimer/pspkvm/tags/pspkvm-v0_3_1-20080408/jsr75/src/config/win32/properties_jsr75.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "../common/configuration.dtd">
<!--
   

  Copyright  1990-2007 Sun Microsystems, Inc. All Rights Reserved.
  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
  
  This program is free software; you can redistribute it and/or
  modify it under the terms of the GNU General Public License version
  2 only, as published by the Free Software Foundation.
  
  This program is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  General Public License version 2 for more details (a copy is
  included at /legal/license.txt).
  
  You should have received a copy of the GNU General Public License
  version 2 along with this work; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
  02110-1301 USA
  
  Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa
  Clara, CA 95054 or visit www.sun.com if you need additional
  information or have any questions.

-->
<!-- System-specific JSR 75 properties required by the specification -->
<configuration>
<properties>
<!-- System  properties (visible via System.getProperty() -->
  <property Key="fileconn.dir.private"
      Value="file:///Private/"
      Scope="system"
      Comment="The private work directory for MIDlet suite."/>

  <property Key="file.separator"
      Value="\\"
      Scope="system"
      Comment="The file separator character(s) for the underlying platform."/>

<!-- Internal properties (visible via Configuration.getProperty() -->
  <property Key="PIMRootDir"
      Value="file:///PIMdb/"
      Scope="internal"
      Comment="The root directory that contains PIM data."/>

  <property Key="DefaultContactList"
      Value="Default_contact"
      Scope="internal"
      Comment="The directory name of the default contact list."/>
		    
  <property Key="DefaultEventList"
      Value="Default_event"
      Scope="internal"
      Comment="The directory name of the default event list."/>
				
  <property Key="DefaultTodoList"
      Value="Default_todo"
      Scope="internal"
      Comment="The directory name of the default todo list."/>							    

  <property Key="file.linebreak"
      Value="\r\n"
      Scope="internal"
      Comment="The which terminates a line in text files."/>
</properties>
</configuration>
